version: '3.7'
services:
  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=app_db